default_config:
logger:
  default: error
  logs:
    custom_components.combined: debug

demo:

camera:
  platform: combined
  base_address: http://localhost:8123
  entities:
    - camera.demo_camera
    - camera.demo_camera